#IanNolon
#5/17/18
#aminoAcid.py

file = open('E_coli_genome.txt')

#replace three letter DNA into one letter acids

for line in file:
    line = line.strip()
    line = line.replace('TTT','F')
    line = line.replace('TTC','F')
    line = line.replace('TTA','L')
    line = line.replace('TTG','L')
    line = line.replace('CTT','L')
    line = line.replace('CTC','L')
    line = line.replace('CTA','L')
    line = line.replace('CTG','L')
    line = line.replace('ATT','I')
    line = line.replace('ATC','I')
    line = line.replace('ATA','I')
    line = line.replace('ATG','M')
    line = line.replace('GTT','V')
    line = line.replace('GTC','V')
    line = line.replace('GTA','V')
    line = line.replace('GTC','V')
    line = line.replace('TCT','S')
    line = line.replace('TCA','S')
    line = line.replace('TCC','S')
    line = line.replace('TCG','S')
    line = line.replace('CCA','P')
    line = line.replace('CCC','P')
    line = line.replace('CCT','P')
    line = line.replace('CCG','P')
    line = line.replace('ACA','Thr')
    line = line.replace('ACC','Thr')
    line = line.replace('ACT','Thr')
    line = line.replace('ACG','Thr')
    line = line.replace('GCA','Ala')
    line = line.replace('GCC','Ala')
    line = line.replace('GCT','Ala')
    line = line.replace('GCG','Ala')
    line = line.replace('TAT','Y')
    line = line.replace('TAC','Y')
    line = line.replace('TAA','Stop')
    line = line.replace('TAG','Stop')
    line = line.replace('CAT','H')
    line = line.replace('CAC','H')
    line = line.replace('CAA','Q')
    line = line.replace('CAG','Q')
    line = line.replace('AAT','N')
    line = line.replace('AAC','N')
    line = line.replace('AAA','K')
    line = line.replace('AAG','K')
    line = line.replace('GAT','D')
    line = line.replace('GAC','D')
    line = line.replace('GAA','E')
    line = line.replace('GAG','E')
    line = line.replace('TGT','Cys')
    line = line.replace('TGC','Cys')
    line = line.replace('TGA','Stop')
    line = line.replace('TGG','W')
    line = line.replace('CGT','R')
    line = line.replace('CGC','R')
    line = line.replace('CGA','R')
    line = line.replace('CGG','R')
    line = line.replace('AGT','S')
    line = line.replace('AGC','S')
    line = line.replace('AGA','R')
    line = line.replace('AGG','R')
    line = line.replace('GGT','Gly')
    line = line.replace('GGC','Gly')
    line = line.replace('GGA','Gly')
    line = line.replace('GGG','Gly')
    line = line.replace('Thr','T')
    line = line.replace('Ala','A')
    line = line.replace('Cys','C')
    line = line.replace('Gly','G')
    print(line)
